#
# A Fedora rawhide image tailored for tmt test suite
#
# tmt/tests/fedora/rawhide/upstream:latest
#

FROM quay.io/fedora/fedora:rawhide

    # Populate dnf cache
RUN    dnf makecache \
    # Make sure the image is built with the latest packages
    && dnf update -y \
