#
# A Fedora rawhide image tailored for tmt test suite
#
# tmt/tests/fedora/rawhide:latest
#

FROM quay.io/fedora/fedora:rawhide

    # Populate dnf cache
RUN    dnf makecache \
    # Inject `dnf5` to make things more complicated for `dnf` family of
    # package manager implementations
    && dnf install -y dnf5
