#
# A Fedora rawhide image tailored for tmt test suite
#

FROM registry.fedoraproject.org/fedora:rawhide

# Inject `dnf5` to make things more complicated for `dnf` family of
# package manager implementations
RUN dnf install -y dnf5
