#
# A Fedora rawhide image tailored for tmt test suite
#
# tmt/tests/fedora/rawhide/upstream:latest
#

FROM quay.io/fedora/fedora:rawhide

RUN <<EOF
set -ex

# Populate dnf cache
dnf makecache

# Make sure the image is built with the latest packages
dnf update -y
EOF
