#
# os_release = {
#   'ANSI_COLOR': '0;31',
#   'BUG_REPORT_URL': 'https://bugzilla.redhat.com/',
#   'CPE_NAME': 'cpe:/o:redhat:enterprise_linux:8::baseos',
#   'DOCUMENTATION_URL': 'https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8',
#   'HOME_URL': 'https://www.redhat.com/',
#   'ID': 'rhel',
#   'ID_LIKE': 'fedora',
#   'NAME': 'Red Hat Enterprise Linux',
#   'PLATFORM_ID': 'platform:el8',
#   'PRETTY_NAME': 'Red Hat Enterprise Linux 8.10 Beta (Ootpa)',
#   'REDHAT_BUGZILLA_PRODUCT': 'Red Hat Enterprise Linux 8',
#   'REDHAT_BUGZILLA_PRODUCT_VERSION': '8.10',
#   'REDHAT_SUPPORT_PRODUCT': 'Red Hat Enterprise Linux',
#   'REDHAT_SUPPORT_PRODUCT_VERSION': '8.10 Beta',
#   'VERSION': '8.10 (Ootpa)',
#   'VERSION_ID': '8.10'
# }
#
- hosts: guest-rhel8
  user: root
  tasks:
    - name: Install package 'epel-release'
      ansible.builtin.yum:
        name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
        disable_gpg_check: true
        state: present
    - name: Install package 'epel-next-release'
      ansible.builtin.yum:
        name: https://dl.fedoraproject.org/pub/epel/epel-next-release-latest-8.noarch.rpm
        disable_gpg_check: true
        state: present
    - name: Install 'dnf config-manager'
      shell: dnf -y install 'dnf-command(config-manager)'
    - name: Enable 'epel' repos
      shell: dnf config-manager --enable epel epel-debuginfo epel-source
    - name: Enable 'epel-next' repos
      shell: dnf config-manager --enable epel-next epel-next-debuginfo epel-next-source
