#
# os_release = {
#     'ANSI_COLOR': '0;31',
#     'BUG_REPORT_URL': 'https://bugzilla.redhat.com/',
#     'CPE_NAME': 'cpe:/o:redhat:enterprise_linux:7.9:GA:server',
#     'HOME_URL': 'https://www.redhat.com/',
#     'ID': 'rhel',
#     'ID_LIKE': 'fedora',
#     'NAME': 'Red Hat Enterprise Linux Server',
#     'PRETTY_NAME': 'Red Hat Enterprise Linux Server 7.9 (Maipo)',
#     'REDHAT_BUGZILLA_PRODUCT': 'Red Hat Enterprise Linux 7',
#     'REDHAT_BUGZILLA_PRODUCT_VERSION': '7.9',
#     'REDHAT_SUPPORT_PRODUCT': 'Red Hat Enterprise Linux',
#     'REDHAT_SUPPORT_PRODUCT_VERSION': '7.9',
#     'VARIANT': 'Server',
#     'VARIANT_ID': 'server',
#     'VERSION': '7.9 (Maipo)',
#     'VERSION_ID': '7.9'
# }
#
- hosts: guest-rhel7
  user: root
  tasks:
    - name: Install package 'epel-release'
      ansible.builtin.yum:
        name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
        state: present
    - name: Install package 'yum-utils'
      ansible.builtin.yum:
        name: yum-utils
        state: present
    - name: Enable repos related to 'epel'
      shell: yum-config-manager --enable epel epel-debuginfo epel-source
