name-template: '$RESOLVED_VERSION'
tag-template: '$RESOLVED_VERSION'
categories:
  - title: '🚀 Highlights'
    labels:
      - 'release note'
  - title: '🔧 Other changes'
    labels:
      - '*'
exclude-labels:
  - 'ignore-for-release'
change-template: '- $TITLE by @$AUTHOR (#$NUMBER)'
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
replacers:
  - search: '/releases\.html#tmt-(\d+)\.(\d+)\.(\d+)/'
    replace: 'releases.html#tmt-$1-$2-$3'
template: |
  See the [release notes](https://tmt.readthedocs.io/en/stable/releases.html#tmt-$RESOLVED_VERSION) for the list of interesting changes.

  $CHANGES

  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...$RESOLVED_VERSION
