#
# A CentOS Stream 9 image tailored for tmt test suite
#
# tmt/tests/centos/stream9/upstream:latest
#

FROM quay.io/centos/centos:stream9

RUN <<EOF
set -ex

# Populate dnf cache
dnf makecache

# Make sure the image is built with the latest packages
dnf update -y
EOF
