specfile_path: tmt.spec
synced_files:
    - tmt.spec

upstream_project_name: tmt
downstream_package_name: tmt


actions:
  create-archive:
  - make tarball
  get-current-version:
  - make version

jobs:
- job: tests
  trigger: pull_request
  metadata:
    targets:
    - fedora-all
    - epel-8

- job: copr_build
  trigger: commit
  metadata:
    branch: main
    targets:
    - fedora-all
    - epel-8
    list_on_homepage: True
    preserve_project: True
    owner: psss
    project: tmt
