specfile_path: tmt.spec
files_to_sync:
  - tmt.spec
  - .packit.yaml

upstream_package_name: tmt
downstream_package_name: tmt

upstream_project_url: https://github.com/teemtee/tmt
issue_repository: https://github.com/teemtee/tmt

srpm_build_deps:
  - hatch
  - python3-hatch-vcs

actions: &base-actions
  create-archive:
    - hatch run docs:man
    - hatch build -t sdist
    - bash -c "ls dist/tmt-*.tar.gz"
  get-current-version:
    - hatch version

targets: &all-targets
  - fedora-all
  - epel-9

# Uncomment below line if OpenScanHub scans are failing
# osh_diff_scan_after_copr_build: false


# Common definitions
_:
  # Copr jobs under the packit project
  - &copr-under-packit
    job: copr_build
    additional_repos:
      - copr://@teemtee/stable

  # Copr jobs under the teemtee project
  - &copr-under-teemtee
    <<: *copr-under-packit
    list_on_homepage: True
    preserve_project: True
    owner: "@teemtee"

  # Test jobs base setup
  - &test-base
    job: tests
    trigger: pull_request
    tf_extra_params:
      environments:
        - &copr-teemtee-stable
          artifacts:
            - type: repository-file
              id: https://copr.fedorainfracloud.org/coprs/g/teemtee/stable/repo/fedora-rawhide/group_teemtee-stable-fedora-rawhide.repo
            - type: repository-file
              id: https://copr.fedorainfracloud.org/coprs/g/teemtee/stable/repo/epel-9/group_teemtee-stable-epel-9.repo

  # Latest fedora & epel targets
  - &latest-targets
    - fedora-latest-stable
    - epel-9

  # Internal jobs
  - &internal
    use_internal_tf: True
    targets:
      - fedora-latest-stable
    tf_extra_params:
      environments:
        - &tmt-cloud-resources
          <<: *copr-teemtee-stable
          settings:
            provisioning:
              tags:
                BusinessUnit: tmt

  # Full test requires
  - &require-full-tests
    require:
      label:
        present:
          - ci | full test
        absent:
          - status | discuss


jobs:
  # Build released bits to stable
  - <<: *copr-under-teemtee
    trigger: release
    project: stable

  # Build commits merged to main to latest
  - <<: *copr-under-teemtee
    trigger: commit
    branch: main
    project: latest
    release_suffix: "{PACKIT_PROJECT_BRANCH}"

  # Build pull requests
  - <<: *copr-under-packit
    trigger: pull_request

  # Test core
  - <<: *test-base
    targets: *latest-targets
    identifier: core
    tmt_plan: '/plans/features/(core|basic)'

  # Test full
  - <<: *test-base
    <<: *require-full-tests
    identifier: full
    # Do not run extended unit tests. That plan gets its own job
    # because of podman vs systemd-resolved flakiness.
    tmt_plan: '^(?!/plans/features/extended-unit-tests).*$'

  # Extended unit tests
  - <<: *test-base
    <<: *require-full-tests
    targets: [ fedora-latest-stable ]
    identifier: extended-unit-tests
    tmt_plan: '/plans/features/extended-unit-tests$'

  # Test virtual & bootc provision plugins
  - <<: *test-base
    <<: *internal
    <<: *require-full-tests
    identifier: provision
    tmt_plan: '/plans/provision/(bootc|virtual)'
    tf_extra_params:
      environments:
        - tmt:
            context:
              how: provision
          <<: *tmt-cloud-resources

  # Test internal plugins
  - <<: *test-base
    <<: *internal
    <<: *require-full-tests
    identifier: internal-plugins
    fmf_url: "https://gitlab.cee.redhat.com/baseos-qe/tmt.git"

  # Test internal wow
  - <<: *test-base
    <<: *internal
    <<: *require-full-tests
    identifier: internal-wow
    fmf_url: "https://gitlab.cee.redhat.com/baseos-qe/integration_scripts.git"
    tmt_plan: '/tmt/integration/plan'

  # Propose downstream pull requests
  - job: propose_downstream
    trigger: release
    dist_git_branches: *all-targets

  # Create koji builds
  - job: koji_build
    trigger: commit
    allowed_pr_authors: ["packit", "all_committers"]
    dist_git_branches: *all-targets

  # Create bodhi updates
  - job: bodhi_update
    trigger: commit
    dist_git_branches:
      - fedora-branched
      - epel-9
