specfile_path: tmt.spec
synced_files:
    - tmt.spec

upstream_project_name: tmt
downstream_package_name: tmt


actions:
  create-archive:
  - make tarball
  get-current-version:
  - make version

jobs:
- job: tests
  trigger: pull_request
  targets:
  - fedora-all
  - epel-8
  - epel-9
  enable_net: False

- job: tests
  trigger: pull_request
  identifier: "internal-plugins"
  targets:
  - fedora-latest-stable
  use_internal_tf: True
  fmf_url: "https://gitlab.cee.redhat.com/baseos-qe/tmt.git"

- job: tests
  trigger: pull_request
  identifier: "internal-wow"
  targets:
  - fedora-latest-stable
  use_internal_tf: True
  fmf_url: "https://gitlab.cee.redhat.com/baseos-qe/integration_scripts.git"
  tmt_plan: "/tmt/integration/plan"

- job: copr_build
  trigger: commit
  branch: main
  targets:
  - fedora-all
  - epel-8
  - epel-9
  enable_net: False
  list_on_homepage: True
  preserve_project: True
  owner: psss
  project: tmt
