specfile_path: tmt.spec
synced_files:
    - tmt.spec

upstream_project_name: tmt
downstream_package_name: tmt

current_version_command: ["make", "packit-version"]

actions:
  create-archive:
  - make packit-tarball
  - make packit-path

jobs:
- job: copr_build
  trigger: pull_request
  metadata:
    targets:
      - fedora-all

- job: tests
  trigger: pull_request
  metadata:
    targets:
    - fedora-all
