-   id: tmt
    name: tmt
    entry: tmt
    files: '.*\.fmf$'
    verbose: true
    pass_filenames: true
    language: python
    language_version: python3

-   id: tmt-lint
    name: tmt lint
    entry: tmt-pre-commit
    files: '.*\.fmf$'
    verbose: false
    pass_filenames: true
    language: python
    language_version: python3

-   id: tmt-tests-lint
    name: tmt tests lint
    entry: tmt-pre-commit --lint-type tests
    files: '.*\.fmf$'
    verbose: false
    pass_filenames: true
    language: python
    language_version: python3

-   id: tmt-plans-lint
    name: tmt plans lint
    entry: tmt-pre-commit --lint-type plans
    files: '.*\.fmf$'
    verbose: false
    pass_filenames: true
    language: python
    language_version: python3

-   id: tmt-stories-lint
    name: tmt stories lint
    entry: tmt-pre-commit --lint-type stories
    files: '.*\.fmf$'
    verbose: false
    pass_filenames: true
    language: python
    language_version: python3
