-   id: tmt-lint
    name: tmt lint
    entry: python -m tmt._pre_commit
    files: '(?:.*\.fmf|.*/\.fmf/version)$'
    verbose: false
    pass_filenames: true
    language: python
    language_version: python3

-   id: tmt-tests-lint
    name: tmt tests lint
    entry: python -m tmt._pre_commit --lint-what tests
    files: '(?:.*\.fmf|.*/\.fmf/version)$'
    verbose: false
    pass_filenames: true
    language: python
    language_version: python3

-   id: tmt-plans-lint
    name: tmt plans lint
    entry: python -m tmt._pre_commit --lint-what plans
    files: '(?:.*\.fmf|.*/\.fmf/version)$'
    verbose: false
    pass_filenames: true
    language: python
    language_version: python3

-   id: tmt-stories-lint
    name: tmt stories lint
    entry: python -m tmt._pre_commit --lint-what stories
    files: '(?:.*\.fmf|.*/\.fmf/version)$'
    verbose: false
    pass_filenames: true
    language: python
    language_version: python3
