#
# A Fedora 39 image tailored for tmt test suite
#
# tmt/tests/fedora/39:latest
#

FROM quay.io/fedora/fedora:39

    # Populate dnf cache
RUN    dnf makecache \
    # Inject `dnf5` to make things more complicated for `dnf` family of
    # package manager implementations
    && dnf install -y dnf5
