#
# A UBI8 image tailored for tmt test suite
#
# tmt/tests/ubi/8/upstream:latest
#

FROM registry.access.redhat.com/ubi8:latest

RUN <<EOF
set -ex

# Populate yum cache
dnf makecache

# Make sure the image is built with the latest packages
dnf update -y
EOF
