#
# A Fedora 41 image tailored for tmt test suite
#
# tmt/tests/fedora/41:latest
#

FROM quay.io/fedora/fedora:41

    # Populate dnf cache
RUN    dnf makecache \
    # Inject `dnf5` to make things more complicated for `dnf` family of
    # package manager implementations
    && dnf install -y dnf5
