#
# An Ubuntu image tailored for tmt test suite
#
# tmt/tests/ubuntu/22.04/upstream:latest
#

FROM docker.io/library/ubuntu:22.04

# hadolint ignore=DL3009
RUN <<EOF
set -ex

# Force using IPv4 for more stable CI
echo 'Acquire::ForceIPv4 "true";' > /etc/apt/apt.conf.d/99force-ipv4

# Populate apt cache
apt-get update

# Make sure the image is built with the latest packages
apt-get upgrade -y
EOF
