#
# An Ubuntu image tailored for tmt test suite
#
# tmt/tests/ubuntu/22.04/upstream:latest
#

FROM docker.io/library/ubuntu:22.04

# hadolint ignore=DL3009
RUN <<EOF
set -ex

# Populate apt cache
apt-get update

# Make sure the image is built with the latest packages
apt-get upgrade -y
EOF
