#
# A Fedora 40 image tailored for tmt test suite
#
# tmt/tests/fedora/40:latest
#

FROM quay.io/fedora/fedora:40

    # Populate dnf cache
RUN    dnf makecache \
    # Inject `dnf5` to make things more complicated for `dnf` family of
    # package manager implementations
    && dnf install -y dnf5
