#
# A Fedora 40 image tailored for tmt test suite
#
# tmt/tests/fedora/40/upstream:latest
#

FROM quay.io/fedora/fedora:40

RUN <<EOF
set -ex

# Populate dnf cache
dnf makecache

# Make sure the image is built with the latest packages
dnf update -y
EOF
