#
# A Fedora 40 image tailored for tmt test suite, with unprivileged account & password-less sudo
#
# tmt/tests/fedora/40/unprivileged:latest
#

FROM quay.io/fedora/fedora:40

    # Populate dnf cache
RUN    dnf makecache \
    # Create unprivileged user and setup sudo for it
    && dnf install -y /usr/sbin/useradd \
    && useradd fedora \
    && usermod -aG wheel fedora \
    && echo -e 'fedora\tALL=(ALL)\tNOPASSWD: ALL' >> /etc/sudoers

USER fedora
