- hosts: all
  user: root
  tasks:
    # RHEL N and CentOS Stream N, where N >= 8
    - when: ansible_distribution == "RedHat" and ansible_distribution_major_version|int >= 8
      block:
        - name: Install 'dnf config-manager'
          shell: dnf -y install 'dnf-command(config-manager)'

        - name: Detect repo 'rhel-CRB' is installed
          command: dnf repoinfo rhel-CRB | grep -E 'Repo-id'
          register: result
          ignore_errors: True

        - name: disable repo of 'rhel-CRB'
          shell: dnf config-manager --disable rhel-CRB
          when: result.rc == 0

    # CentOS Stream N where N >= 8
    - when: ansible_distribution == "CentOS" and ansible_distribution_major_version|int >= 8
      block:
        - name: Install 'dnf config-manager'
          shell: dnf -y install 'dnf-command(config-manager)'

        - name: Detect repo 'crb' is installed
          command: dnf repoinfo crb | grep -E 'Repo-id'
          register: result
          ignore_errors: True

        - name: disable repo of 'crb'
          shell: dnf config-manager --disable crb
          when: result.rc == 0
