- hosts: all
  user: root
  tasks:
    - when: ansible_distribution_major_version == "7"
      block:
        - name: Install package 'yum-utils'
          ansible.builtin.yum:
            name: yum-utils
            state: present
        - name: Disable repos of 'epel'
          shell: yum-config-manager --disable epel epel-debuginfo epel-source

    - when: ansible_distribution_major_version == "8" or ansible_distribution_major_version == "9"
      block:
        - name: Install 'dnf config-manager'
          shell: dnf -y install 'dnf-command(config-manager)'
        - name: Disable repos of 'epel'
          shell: dnf config-manager --disable epel epel-debuginfo epel-source
        - name: Disable repos of 'epel-next'
          shell: dnf config-manager --disable epel-next epel-next-debuginfo epel-next-source
