- hosts: all
  user: root
  tasks:
    # RHEL 7 or CentOS 7, fail it for the time being
    # XXX: Not sure it should be implemented. For details, please refer to:
    #      https://github.com/beakerlib/crypto/blob/master/fips/lib.sh#L143
    - when: ansible_distribution_major_version == "7"
      block:
        - name: Enable fips
          command: exit 1

    # RHEL N or CentOS Stream N where N >= 8
    - when: ansible_distribution_major_version|int >= 8
      block:
        - name: Install package 'crypto-policies-scripts'
          ansible.builtin.yum:
            name: crypto-policies-scripts
            state: present
        - name: Disable fips
          command: fips-mode-setup --disable
