#
# A Fedora CoreOS image tailored for tmt test suite
#
# Similar to `Containerfile.coreos`, but aims to simulate ostree-booted environment
#

FROM quay.io/fedora/fedora-coreos:stable

    # Inject `dnf` to make things more complicated for `rpm-ostree` package
    # manager implementation
RUN rpm-ostree install dnf5 \
    # Remove diffutils as its used in many package manager tests, and tests
    # are simpler if all environments lack the same package, we don't have
    # to parametrize them even more.
    && dnf5 remove -y diffutils \
    # Simulate ostree-booted environment
    && touch /run/ostree-booted
