#
# A Fedora CoreOS image tailored for tmt test suite
#
# Similar to `Containerfile.coreos`, but aims to simulate ostree-booted environment
#
# tmt/tests/fedora/coreos/ostree:latest
#

FROM quay.io/fedora/fedora-coreos:stable

RUN <<EOF
set -ex

# Inject `dnf` to make things more complicated for `rpm-ostree` package
# manager implementation
rpm-ostree install dnf5

# Populate dnf cache
dnf5 makecache

# Make sure the image is built with the latest packages
dnf5 update -y

# Simulate ostree-booted environment
touch /run/ostree-booted
EOF
