#
# A Debian image tailored for tmt test suite
#
# tmt/tests/debian/12.7/upstream:latest
#

FROM docker.io/library/debian:12.7

# hadolint ignore=DL3009
RUN <<EOF
set -ex

# Populate apt cache
apt-get update

# Make sure the image is built with the latest packages
apt-get upgrade -y
EOF
