#
# A Debian image tailored for tmt test suite
#
# tmt/tests/debian/12.7/upstream:latest
#

FROM docker.io/library/debian:12.7

    # Populate apt cache
RUN    apt update \
    # Make sure the image is built with the latest packages
    && apt upgrade -y
