execute:
    how: tmt
discover:
    how: shell
    tests:
    - name: booted image
      test: bootc status && bootc status | grep localhost/tmtbase
provision:
    how: bootc
    add-tmt-dependencies: false
    container-file: "$TMT_BOOTC_CONTAINERFILE_RUNDIR/includes_deps.containerfile"
    container-file-workdir: .
    disk: 20
