execute:
    how: tmt
discover:
    how: shell
    tests:
    - name: booted image
      test: bootc status | grep localhost/tmtmodified
provision:
    how: bootc
    add-tmt-dependencies: true
    container-file: "$TMT_BOOTC_CONTAINERFILE_RUNDIR/needs_deps.containerfile"
    container-file-workdir: .
    disk: 20
