#
# A Fedora CoreOS image tailored for tmt test suite
#
# tmt/tests/fedora/coreos:latest
#

FROM quay.io/fedora/fedora-coreos:stable

RUN <<EOF
set -ex

# Inject `dnf` to make things more complicated for `rpm-ostree` package
# manager implementation
rpm-ostree install dnf5

# Populate dnf cache
dnf5 makecache

# Make sure the image is built with the latest packages
dnf5 update -y
EOF
