#
# A Fedora CoreOS image tailored for tmt test suite
#
# tmt/tests/fedora/coreos:latest
#

FROM quay.io/fedora/fedora-coreos:stable

    # Inject `dnf` to make things more complicated for `rpm-ostree` package
    # manager implementation
RUN    rpm-ostree install dnf5 \
    # Populate dnf cache
    && dnf5 makecache
