name: Build and publish renovate image
on:
  push:
    paths:
      - containers/Containerfile.renovate
    branches: [main]
  workflow_dispatch:
    inputs:
      ref:
        description: Committish to build and publish
        required: true

permissions: {}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          ref: ${{ inputs.ref }}
          persist-credentials: false
      - uses: redhat-actions/buildah-build@7a95fa7ee0f02d552a32753e7414641a04307056 # v2.13
        with:
          image: renovate-tmt
          containerfiles: ./containers/Containerfile.renovate
      - uses: redhat-actions/push-to-registry@5ed88d269cf581ea9ef6dd6806d01562096bee9c # v2.8
        with:
          image: renovate-tmt
          tags: latest
          registry: ghcr.io/teemtee
          username: ${{ github.actor }}
          password: ${{ github.token }}
