name: Build and publish renovate image
on:
  push:
    paths:
      - containers/Containerfile.renovate
    branches: [main]
  workflow_dispatch:
    inputs:
      ref:
        description: Committish to build and publish
        required: true

permissions: {}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          ref: ${{ inputs.ref }}
          persist-credentials: false
      - uses: redhat-actions/buildah-build@719e3c40d8af9790c23eca13f7daa339f2867034 # v3.1.0
        with:
          image: renovate-tmt
          containerfiles: ./containers/Containerfile.renovate
      - uses: redhat-actions/push-to-registry@94ade333c38ecc0e60e94785125d9a52ca423b37 # v3.0.0
        with:
          image: renovate-tmt
          tags: latest
          registry: ghcr.io/teemtee
          username: ${{ github.actor }}
          password: ${{ github.token }}
