name: gen-files
run-name: Generate files

on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read

env:
  HATCH_ENV_TYPE_VIRTUAL_PATH: ${{ github.workspace }}/.hatch_envs

jobs:
  man:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-docs-env
      - name: Generate man file and check if it changed anything
        run: |
          hatch run docs:man
          git diff --exit-code
