name: publish_images
on: workflow_dispatch

permissions: {}

jobs:
  publish-images:
    runs-on: ubuntu-latest
    environment:
      name: quay.io
      url: https://quay.io/organization/teemtee

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Build - tmt
        uses: redhat-actions/buildah-build@719e3c40d8af9790c23eca13f7daa339f2867034 # v3.1.0
        id: build-image-tmt
        with:
          image: tmt
          containerfiles: ./containers/Containerfile.mini
      - name: Build - tmt-all
        uses: redhat-actions/buildah-build@719e3c40d8af9790c23eca13f7daa339f2867034 # v3.1.0
        id: build-image-tmt-all
        with:
          image: tmt-all
          containerfiles: ./containers/Containerfile.full
      - name: Push To quay.io - tmt
        id: push-to-quay-tmt
        uses: redhat-actions/push-to-registry@94ade333c38ecc0e60e94785125d9a52ca423b37 # v3.0.0
        with:
          image: ${{ steps.build-image-tmt.outputs.image }}
          tags: ${{ steps.build-image-tmt.outputs.tags }}
          registry: quay.io/teemtee
          username: teemtee+github_action
          password: ${{ secrets.QUAY_TEEMTEE_SECRET }}
      - name: Push To quay.io - tmt-all
        id: push-to-quay-tmt-all
        uses: redhat-actions/push-to-registry@94ade333c38ecc0e60e94785125d9a52ca423b37 # v3.0.0
        with:
          image: ${{ steps.build-image-tmt-all.outputs.image }}
          tags: ${{ steps.build-image-tmt-all.outputs.tags }}
          registry: quay.io/teemtee
          username: teemtee+github_action
          password: ${{ secrets.QUAY_TEEMTEE_SECRET }}
