name: release
run-name: Release ${{ inputs.ref || github.ref_name }}

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      ref:
        type: string
        description: 'Tag to release'
        required: true

permissions: {}

jobs:
  build:
    uses: ./.github/workflows/step-build-wheel.yml
    with:
      ref: ${{ inputs.ref }}

  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/tmt
    permissions:
      id-token: write
      attestations: write

    steps:
      - uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c  # v8
        with:
          name: Packages
          path: dist

      - name: Generate artifact attestation for sdist and wheel
        uses: actions/attest-build-provenance@a2bbfa25375fe432b6a289bc6b6cd05ecd0c4c32  # v4
        with:
          subject-path: "dist/*"

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@cef221092ed1bacb1cc03d23a2d87d1d172e277b  # release/v1
