name: Build wheel

on:
  workflow_call:
    inputs:
      ref:
        type: string
        description: Committish to build

permissions: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6
        with:
          ref: ${{ inputs.ref }}
          persist-credentials: false
      - uses: hynek/build-and-inspect-python-package@fe0a0fb1925ca263d076ca4f2c13e93a6e92a33e  # v2
