name: Pre-commit

on:
  workflow_call:
    inputs:
      ref:
        type: string
        description: Committish to test

permissions: {}

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    env:
      SKIP: no-commit-to-branch
    steps:
    # Required because of https://github.com/hadolint/hadolint/issues/886
    - run: |
        wget -O /usr/local/bin/hadolint https://github.com/hadolint/hadolint/releases/latest/download/hadolint-Linux-x86_64
        chmod +x /usr/local/bin/hadolint
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      with:
        persist-credentials: false
        ref: ${{ inputs.ref }}
    - uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
      with:
        # Python 3.9 is for mypy testing the lowest python version
        # Python 3.13 is for ansible-lint hard-coding the python requirement
        python-version: |
          3.9
          3.13
          3.x
    - uses: pre-commit/action@2c7b3805fd2a0fd8c1884dcaebf91fc102a13ecd # v3.0.1
