name: Documentation tests

on:
  workflow_call:
    inputs:
      ref:
        type: string
        description: Committish to test

permissions: {}

jobs:
  doc-test:
    name: Sphinx (${{ matrix.builder }})
    runs-on: ubuntu-latest
    if: "!contains(github.event.pull_request.labels.*.name, 'ci | skip')"
    strategy:
      fail-fast: false
      matrix:
        builder: [ linkcheck, html, lint ]
        include:
          # Run default html builder with warnings as error
          - builder: html
            args: -W
          - builder: lint
            sphinx_builder: html

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
          ref: ${{ inputs.ref }}
      - uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: 3.x
      - uses: astral-sh/setup-uv@c771a70e6277c0a99b617c7a806ffedaca235ff9 # v9.0.0
        with:
          activate-environment: true
      - name: Install tmt[docs]
        run: uv sync --frozen --extra docs

      # TODO: Move this to its own extra/group
      - name: Install other test dependencies
        run: uv pip install sphinx-lint
        if: ${{ matrix.builder == 'lint' }}

      - name: Get date
        id: date
        run: |
          echo "date=$(/usr/bin/date -u '+%Y%m%d')" >> $GITHUB_OUTPUT
        if: ${{ matrix.builder == 'linkcheck' }}
      - name: Cache linkcheck results
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: docs/_build/linkcheck_cache.json
          key: linkcheck-${{ steps.date.outputs.date }}
          restore-keys: |
            linkcheck-
        if: ${{ matrix.builder == 'linkcheck' }}

      - name: Run sphinx builder ${{ matrix.sphinx_builder || matrix.builder }}
        run: sphinx-build -E -b ${{ matrix.sphinx_builder || matrix.builder }} ${{ matrix.args }} docs/ docs/_build

      # TODO: enable all checks
      # https://github.com/sphinx-contrib/sphinx-lint/issues/74
      - name: Run Sphinx ReST linter
        run: sphinx-lint --ignore=docs/_build docs tmt tests
        if: ${{ matrix.builder == 'lint' }}
