name: Pre-commit

on:
  workflow_call:
    inputs:
      ref:
        type: string
        description: Committish to test

permissions: {}

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    env:
      SKIP: no-commit-to-branch
    steps:
    # Required because of https://github.com/hadolint/hadolint/issues/886
    - run: |
        wget -O /usr/local/bin/hadolint https://github.com/hadolint/hadolint/releases/latest/download/hadolint-Linux-x86_64
        chmod +x /usr/local/bin/hadolint
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6
      with:
        persist-credentials: false
        ref: ${{ inputs.ref }}
    - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405  # v6
      with:
        # Python 3.9 is for mypy testing the lowest python version
        # Python 3.13 is for ansible-lint hard-coding the python requirement
        python-version: |
          3.9
          3.13
          3.x
    - uses: pre-commit/action@2c7b3805fd2a0fd8c1884dcaebf91fc102a13ecd  # v3.0.1
