#
# A CentOS Stream 10 image tailored for tmt test suite
#
# tmt/tests/centos/stream10:latest
#

FROM quay.io/centos/centos:stream10

RUN <<EOF
set -ex

# Populate dnf cache
dnf makecache

# Make sure the image is built with the latest packages
dnf update -y
EOF
